import { Button, Container } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import { userPool } from "../lib/cognito";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container mt={10}>
          <Link href="/auth" passHref>
            <Button as="a">Connect</Button>
          </Link>
        </Container>
      </main>
    </div>
  );
}
